name: Deploy JHipster Application to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build Backend with Maven
        run: ./mvnw -Pprod clean package -DskipTests

      - name: Build Frontend
        run: |
          chmod +x ./npmw
          ./npmw install
          ./npmw run build
      - name: Package Frontend
        run: tar -czf frontend.tar.gz -C target/classes static

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            target/monorsm-0.0.1-SNAPSHOT.jar
            frontend.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create SSH key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/aws-key2.pem
          chmod 600 ~/.ssh/aws-key2.pem

      - name: Add EC2 instance to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 16.170.221.137 >> ~/.ssh/known_hosts

      - name: Deploy Backend and Frontend to EC2
        run: |
          # Copy backend and frontend artifacts to EC2
          scp -i ~/.ssh/aws-key2.pem monorsm-0.0.1-SNAPSHOT.jar ubuntu@16.170.221.137:/home/ubuntu/
          scp -i ~/.ssh/aws-key2.pem frontend.tar.gz ubuntu@16.170.221.137:/home/ubuntu/
          
          # Connect to EC2 and set up the environment
          ssh -i ~/.ssh/aws-key2.pem ubuntu@16.170.221.137 <<EOF
            # Update system and install dependencies
            sudo apt update -y
            sudo apt install -y openjdk-17-jdk nodejs npm
            
            # Start Backend
            nohup java -jar /home/ubuntu/monorsm-0.0.1-SNAPSHOT.jar > backend.log 2>&1 &
            
            # Extract and Start Frontend
            cd /home/ubuntu
            tar -xzf frontend.tar.gz
            cd dist/
            nohup npx http-server -p 3000 > frontend.log 2>&1 &
            EOF