name: Deploy JHipster Application to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: service
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -Pprod clean package -DskipTests

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/monorsm-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # permissions:
    #   id-token: write
    #   contents: read

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # - name: Print Environment Variables
      #     run: printenv
      - name: Create SSH key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/aws-key.pem
          chmod 600 ~/.ssh/aws-key.pem

      - name: Add EC2 instance to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.60.42.147 >> ~/.ssh/known_hosts
      - name: Deploy to EC2
        run: |
          scp -i ~/.ssh/aws-key.pem monorsm-0.0.1-SNAPSHOT.jar ec2-user@13.60.42.147:/home/ec2-user/
          ssh -i ~/.ssh/aws-key.pem ec2-user@13.60.42.147 << EOF
          sudo yum update -y
          sudo yum install java-17-openjdk -y
          nohup java -jar /home/ec2-user/monorsm-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
