deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: app-jar

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create SSH key for EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/aws-key.pem
        chmod 600 ~/.ssh/aws-key.pem

    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/aws-key.pem monorsm-0.0.1-SNAPSHOT.jar ec2-user@13.60.42.147:/home/ec2-user/
        ssh -i ~/.ssh/aws-key.pem ec2-user@13.60.42.147 << EOF
        sudo yum update -y
        sudo yum install java-17-openjdk -y
        nohup java -jar /home/ec2-user/monorsm-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
        EOF
